title: Bilal Ghanem # your name (or website title) here
logo: "/images/pp.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  PostDoc researcher at the University of Alberta.
  Department of Computing Science.
  <br><br>
  <a href="https://www.linkedin.com/in/bilalghanem/">LinkedIn</a>
  <br><br>
  <a href="https://scholar.google.es/citations?user=mjrzZZcAAAAJ&hl=en">Google Scholar</a>

theme: jekyll-theme-minimal
google_analytics: UA-162797263-1 # your Google Analytics tracking ID here
