title: Bilal Ghanem # your name (or website title) here
logo: "/images/pp2.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Sr Principal, Quantitative Analytics and Data Science
  
  Gartner
  <br><br>
  <a href="/pdf/Bilal_Ghanem___CV.pdf">CV</a>
  <br>
  <a href="https://www.linkedin.com/in/bilalghanem/">LinkedIn</a>
  <br>
  <a href="https://scholar.google.es/citations?user=mjrzZZcAAAAJ&hl=en">Google Scholar</a>

remote_theme: pages-themes/minimal@v0.2.0 #theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
google_analytics: UA-162797263-1 # your Google Analytics tracking ID here
